---
  env:
    node: true
    es6: true
  rules:
    indent: 1
    prefer-const: 1
    no-var: 1
    prefer-arrow-callback: 1
    no-const-assign: 1
    arrow-spacing: 1
    no-unreachable: 1
    no-unexpected-multiline: 1
    semi:
      - 1
      - never
    space-in-parens: 1
    space-before-function-paren:
      - 1
      - never
    space-infix-ops: 1
    space-before-blocks: 1
    keyword-spacing: 1
    quotes:
      - 1
      - single
    padded-blocks:
      - 1
      - never
    operator-linebreak: 1
    operator-assignment:
      - 1
      - never
    one-var:
      - 1
      - never
    no-trailing-spaces: 1
    no-spaced-func: 1
    no-multiple-empty-lines: 1
    no-mixed-spaces-and-tabs: 1
    no-array-constructor: 1
    new-cap: 1
    linebreak-style: 1
    comma-style: 1
    comma-spacing: 1
    camelcase: 1
    brace-style: 1
    array-bracket-spacing: 1
    no-sync: 1
    global-require: 1
    init-declarations: 1
    no-unused-vars: 1
    no-undef: 1
    no-unused-expressions: 1
    no-return-assign: 1
    no-redeclare: 1
    no-param-reassign: 1
    no-multi-spaces: 1
    no-lone-blocks: 1
    no-fallthrough: 1
    no-empty-function: 1
    no-else-return: 1
    eqeqeq: 1
    dot-notation: 1
    curly: 1
    consistent-return: 1
    comma-dangle:
      - 1
      - always-multiline
    no-cond-assign: 1
    no-constant-condition: 1
    no-dupe-args: 1
    no-dupe-keys: 1
    no-empty: 1
    no-extra-parens: 1
    no-func-assign: 1
    no-irregular-whitespace: 1
    max-statements: 1
    max-len: 1
    template-curly-spacing: 1
    no-useless-concat: 1
    no-magic-numbers: 1
